# Generated by Django 5.1.4 on 2026-07-03 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_type', models.CharField(choices=[('red_bourbon', 'Red Bourbon'), ('arabica', 'Arabica'), ('bourbon_mayaguez', 'Bourbon Mayaguez'), ('jackson', 'Jackson'), ('robusta', 'Robusta')], max_length=32)),
                ('price_type', models.CharField(choices=[('farmgate', 'Farm Gate'), ('cooperative', 'Cooperative'), ('export', 'Export (USD)')], default='farmgate', max_length=20)),
                ('currency', models.CharField(choices=[('RWF', 'Rwandan Franc'), ('USD', 'US Dollar')], default='RWF', max_length=3)),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recorded_date', models.DateField()),
                ('season', models.CharField(blank=True, choices=[('main_harvest', 'Main Harvest (Mar-Jul)'), ('fly_crop', 'Fly Crop (Sep-Dec)'), ('off_season', 'Off Season')], max_length=20)),
                ('market_trend', models.CharField(choices=[('up', 'Rising'), ('down', 'Falling'), ('stable', 'Stable')], default='stable', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cooperative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='cooperatives.cooperative')),
            ],
            options={
                'db_table': 'coffee_prices',
                'ordering': ('-recorded_date',),
                'indexes': [models.Index(fields=['coffee_type', 'price_type', 'recorded_date'], name='coffee_pric_coffee__0e71fc_idx')],
            },
        ),
    ]
