# Generated by Django 5.1.4 on 2026-07-03 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_message', models.TextField()),
                ('notification_date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ('-notification_date',),
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_type', models.CharField(choices=[('red_bourbon', 'Red Bourbon'), ('arabica', 'Arabica'), ('bourbon_mayaguez', 'Bourbon Mayaguez'), ('jackson', 'Jackson'), ('robusta', 'Robusta')], max_length=32)),
                ('price_type', models.CharField(choices=[('farmgate', 'Farm Gate'), ('cooperative', 'Cooperative'), ('export', 'Export (USD)')], default='farmgate', max_length=20)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=12)),
                ('direction', models.CharField(choices=[('above', 'Rises above'), ('below', 'Falls below')], default='above', max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'price_alerts',
                'ordering': ('-created_at',),
            },
        ),
    ]
