"""Build a one-page PDF summary for a prediction, with a trend chart."""
from __future__ import annotations

import io
from datetime import date, timedelta

import matplotlib

matplotlib.use("Agg")  # headless backend
import matplotlib.pyplot as plt  # noqa: E402
from reportlab.lib import colors  # noqa: E402
from reportlab.lib.pagesizes import A4  # noqa: E402
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle  # noqa: E402
from reportlab.lib.units import cm  # noqa: E402
from reportlab.platypus import (  # noqa: E402
    Image,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from prices.models import CoffeePrice


def _trend_chart(prediction) -> io.BytesIO:
    history = list(
        CoffeePrice.objects.filter(
            coffee_type=prediction.coffee_type, price_type=prediction.price_type
        ).order_by("recorded_date")
    )
    dates = [h.recorded_date for h in history]
    prices = [float(h.market_price) for h in history]

    fig, ax = plt.subplots(figsize=(6.5, 3.0))
    if dates:
        ax.plot(dates, prices, color="#1FAE4B", linewidth=1.8, label="Historical")
        future = (dates[-1] if dates else date.today()) + timedelta(days=prediction.horizon_days)
        ax.scatter([future], [float(prediction.predicted_price)], color="#F97316", zorder=5, label="Predicted")
        if prediction.predicted_price_low and prediction.predicted_price_high:
            ax.fill_between(
                [dates[-1], future],
                [prices[-1], float(prediction.predicted_price_low)],
                [prices[-1], float(prediction.predicted_price_high)],
                color="#F97316", alpha=0.15,
            )
    ax.set_title(f"{prediction.coffee_type} — {prediction.price_type} price trend")
    ax.set_ylabel(f"Price ({prediction.currency})")
    ax.legend(loc="best", fontsize=8)
    ax.grid(True, alpha=0.3)
    fig.autofmt_xdate()
    fig.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=120)
    plt.close(fig)
    buf.seek(0)
    return buf


def build_prediction_pdf(prediction) -> io.BytesIO:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, title="IgiciroHub Prediction Report")
    styles = getSampleStyleSheet()
    green = ParagraphStyle("green", parent=styles["Title"], textColor=colors.HexColor("#1FAE4B"))

    story = [
        Paragraph("IgiciroHub — Coffee Price Prediction Report", green),
        Spacer(1, 0.3 * cm),
        Paragraph(f"Generated: {date.today():%d %b %Y}", styles["Normal"]),
        Spacer(1, 0.5 * cm),
    ]

    rows = [
        ["Coffee type", prediction.coffee_type],
        ["Price type", prediction.price_type],
        ["Current price", f"{prediction.current_price} {prediction.currency}"],
        ["Predicted price", f"{prediction.predicted_price} {prediction.currency}"],
        ["Predicted range", f"{prediction.predicted_price_low} – {prediction.predicted_price_high} {prediction.currency}"],
        ["Expected change", f"{prediction.change_pct:+.2f}%"],
        ["Horizon", f"{prediction.horizon_days} days"],
        ["Method", prediction.algorithm_used],
        ["Model accuracy", f"{prediction.accuracy_rate:.1f}%" if prediction.accuracy_rate else "n/a"],
        ["Confidence", prediction.confidence],
    ]
    table = Table(rows, colWidths=[5 * cm, 10 * cm])
    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#E8F7EE")),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ])
    )
    story.append(table)
    story.append(Spacer(1, 0.5 * cm))

    story.append(Image(_trend_chart(prediction), width=16 * cm, height=7.4 * cm))
    story.append(Spacer(1, 0.4 * cm))

    story.append(Paragraph("AI Recommendation", styles["Heading2"]))
    story.append(Paragraph(prediction.recommendation or "—", styles["Normal"]))
    story.append(Spacer(1, 0.6 * cm))
    story.append(
        Paragraph(
            "<i>Prediction generated by IgiciroHub using a Random Forest model on "
            "historical coffee prices. Indicative only.</i>",
            styles["Italic"],
        )
    )

    doc.build(story)
    buf.seek(0)
    return buf
