# Generated by Django 5.1.4 on 2026-07-03 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_type', models.CharField(choices=[('red_bourbon', 'Red Bourbon'), ('arabica', 'Arabica'), ('bourbon_mayaguez', 'Bourbon Mayaguez'), ('jackson', 'Jackson'), ('robusta', 'Robusta')], max_length=32)),
                ('quality_grade', models.CharField(choices=[('AA', 'Grade AA'), ('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C')], default='A', max_length=4)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='RWF', max_length=3)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='listings/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='cooperatives.cooperative')),
            ],
            options={
                'db_table': 'crop_listings',
                'ordering': ('-created_at',),
            },
        ),
    ]
